<?php

use Illuminate\Database\Seeder;

class ClientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //factory(App\Models\Client::class)->create([
        //    'creator_id' => 1,
        //    'owner_id' => 3,
        //    'name' => 'Shawn Thompson',
        //    'email' => 'stjffkldsjsfl@email.com',
        //    'phone' => '578389893443',
        //    'address1' => '60 East HWY',
        //    'city' => 'Owingsville',
        //    'province_id' => 17,
        //    'postal_code' => '40360',
        //    'description' => 'at gas station',
        //]);

        //factory(App\Models\Client::class)->create([
        //    'creator_id' => 1,
        //    'owner_id' => 3,
        //    'name' => 'Powerball',
        //    'email' => 'kaitlyn59@hotmail.com"',
        //    'phone' => '651.208.2071 x652',
        //    'address1' => '9165 Hayes Roads',
        //    'city' => 'Alyssonhaven',
        //    'province_id' => 10,
        //    'postal_code' => '69691-4964',
        //    'description' => 'National Powerball lottery.',
        //]);

        //factory(App\Models\Client::class)->create([
        //    'creator_id' => 1,
        //    'owner_id' => 3,
        //    'name' => 'Mega Millions',
        //    'email' => 'ktorp@kuhn.com',
        //    'phone' => '1-636-997-1169 x6674',
        //    'address1' => '6700 Forrest Hills Suite 163',
        //    'city' => 'Lake Alisa',
        //    'province_id' => 45,
        //    'postal_code' => '26222-7051',
        //    'description' => 'National Mega Millions lottery.',
        //]);

        factory(App\Models\Client::class)->create([            
            "id" => 1,
            "creator_id" => 1,
            "owner_id" => 3,
            "name" => "Shawn Thompson",
            "email" => "stjffkldsjsfl@email.com",
            "phone" => "578389893443",
            "address1" => "60 East HWY",
            "address2" => null,
            "city" => "Owingsville",
            "province_id" => 17,
            "postal_code" => "40360",
            "description" => "at gas station",
            "deleted_at" => null,
            "created_at" => "2018-04-13 14:26:50",
            "updated_at" => "2018-04-13 14:26:50",
        ]);
        
        factory(App\Models\Client::class)->create([
            "id" => 2,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Amanda Conkright",
            "email" => null,
            "phone" => "859-404-0941",
            "address1" => "644 Bell Farm Rd.",
            "address2" => null,
            "city" => "Jeffersonville",
            "province_id" => 17,
            "postal_code" => "40337",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-13 15:48:15",
            "updated_at" => "2018-04-13 15:48:15",
        ]);
        
        factory(App\Models\Client::class)->create([                       
            "id" => 3,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Omar Risner",
            "email" => null,
            "phone" => "606-481-9864",
            "address1" => "139 Stokley Loop",
            "address2" => null,
            "city" => "Clay City",
            "province_id" => 17,
            "postal_code" => "40312",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 10:53:37",
            "updated_at" => "2018-04-18 10:53:37",
        ]);
        
        factory(App\Models\Client::class)->create([            
            "id" => 4,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Omer Risner",
            "email" => null,
            "phone" => "606-481-9864",
            "address1" => "139 Stokley Loop",
            "address2" => null,
            "city" => "Clay City",
            "province_id" => 17,
            "postal_code" => "40312",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:02:50",
            "updated_at" => "2018-04-18 11:02:50",
        ]);
        
        factory(App\Models\Client::class)->create([            
            "id" => 5,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Ann Belle Shultz",
            "email" => null,
            "phone" => "606-674-2673",
            "address1" => "57 Pulpwood road",
            "address2" => null,
            "city" => "Olympia",
            "province_id" => 17,
            "postal_code" => "40362",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:13:16",
            "updated_at" => "2018-04-18 11:13:16",
        ]);
        
        factory(App\Models\Client::class)->create([            
            "id" => 6,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Madilee Risner, Minor Child",
            "email" => null,
            "phone" => "606-481-2848",
            "address1" => "1279 Black Creek Road",
            "address2" => null,
            "city" => "Clay City",
            "province_id" => 17,
            "postal_code" => "40312",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:20:36",
            "updated_at" => "2018-04-18 11:20:36",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 7,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Harold Stephens",
            "email" => "shellyjacob@gmail.com",
            "phone" => "502-662-2949",
            "address1" => null,
            "address2" => null,
            "city" => null,
            "province_id" => 17,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:29:57",
            "updated_at" => "2018-04-18 11:29:57",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 8,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Johnny Flannery",
            "email" => null,
            "phone" => "606-359-4501",
            "address1" => "71 New Comer Road",
            "address2" => null,
            "city" => "Ezel",
            "province_id" => 17,
            "postal_code" => "41472",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:44:13",
            "updated_at" => "2018-04-18 11:44:13",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 9,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Joni Napier",
            "email" => null,
            "phone" => "606-568-7969",
            "address1" => "239 Turner Drive",
            "address2" => null,
            "city" => "Jackson",
            "province_id" => 17,
            "postal_code" => "41339",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:48:44",
            "updated_at" => "2018-04-18 11:48:44",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 10,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Randall White",
            "email" => null,
            "phone" => "606-336-5086",
            "address1" => "401 Kendall Springs Road",
            "address2" => null,
            "city" => "owingsville",
            "province_id" => 17,
            "postal_code" => "40360",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:55:29",
            "updated_at" => "2018-04-18 11:55:29",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 11,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Courtney Nixon",
            "email" => null,
            "phone" => "859-398-5991",
            "address1" => "304 Ford Avenue",
            "address2" => null,
            "city" => "Mount Sterling",
            "province_id" => 17,
            "postal_code" => "40353",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 11:57:37",
            "updated_at" => "2018-04-18 11:57:37",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 12,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Marilyn Sorrell",
            "email" => null,
            "phone" => "859-432-0867 or 859-587-2456",
            "address1" => "200 Antwerp Avenue",
            "address2" => null,
            "city" => "Mount Sterling",
            "province_id" => 17,
            "postal_code" => "40353",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 12:01:29",
            "updated_at" => "2018-04-18 12:01:29",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 13,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Alberta Maze",
            "email" => null,
            "phone" => "606-683-2743",
            "address1" => "558 Cave Run Lake Road",
            "address2" => null,
            "city" => "Salt Lick",
            "province_id" => 17,
            "postal_code" => "40371",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-18 12:20:20",
            "updated_at" => "2018-04-18 12:20:20",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 14,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Gordon Hardin",
            "email" => null,
            "phone" => "606-356-4535",
            "address1" => "95 Ravenswood",
            "address2" => null,
            "city" => "Clearfield",
            "province_id" => 17,
            "postal_code" => "40313",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-25 15:05:13",
            "updated_at" => "2018-04-25 15:05:13",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 15,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Stefani wright",
            "email" => null,
            "phone" => null,
            "address1" => null,
            "address2" => null,
            "city" => null,
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-04-25 15:48:54",
            "updated_at" => "2018-04-25 15:48:54",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 16,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Cheryl Abshear",
            "email" => null,
            "phone" => "(859) 382 - 4031",
            "address1" => null,
            "address2" => null,
            "city" => null,
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 13:17:22",
            "updated_at" => "2018-05-02 13:17:22",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 17,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Tiffany Barnett",
            "email" => null,
            "phone" => null,
            "address1" => null,
            "address2" => null,
            "city" => null,
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 13:23:48",
            "updated_at" => "2018-05-02 13:23:48",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 18,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Colbert Rapheal",
            "email" => null,
            "phone" => "(859) 354 - 7911",
            "address1" => "102 Nicole Court",
            "address2" => null,
            "city" => "Nicholasville",
            "province_id" => 17,
            "postal_code" => "40356",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 13:38:46",
            "updated_at" => "2018-05-02 13:38:46",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 19,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Robin Covarrubias",
            "email" => null,
            "phone" => "(859) 536 - 1128",
            "address1" => "138 N. Main Street",
            "address2" => null,
            "city" => "Mt. Sterling",
            "province_id" => 17,
            "postal_code" => "40353",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 13:42:11",
            "updated_at" => "2018-05-02 13:42:11",
        ]);
        
        factory(App\Models\Client::class)->create([                                    
            "id" => 20,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Andrew Minor",
            "email" => null,
            "phone" => null,
            "address1" => "407 Bluestone Road",
            "address2" => null,
            "city" => "Morehead",
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 13:53:30",
            "updated_at" => "2018-05-02 13:53:30",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 21,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Andrew Minor",
            "email" => null,
            "phone" => null,
            "address1" => "407 Bluestone Road",
            "address2" => null,
            "city" => "Morehead",
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 13:53:35",
            "updated_at" => "2018-05-02 13:53:35",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 22,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Andrew Minor",
            "email" => null,
            "phone" => null,
            "address1" => "407 Bluestone Road",
            "address2" => null,
            "city" => "Morehead",
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:00:50",
            "updated_at" => "2018-05-02 14:00:50",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 23,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Andrew Minor",
            "email" => null,
            "phone" => null,
            "address1" => "407 Bluestone Road",
            "address2" => null,
            "city" => "Morehead",
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:01:05",
            "updated_at" => "2018-05-02 14:01:05",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 24,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Andrew Minor",
            "email" => null,
            "phone" => null,
            "address1" => "407 Bluestone Road",
            "address2" => null,
            "city" => "Morehead",
            "province_id" => 17,
            "postal_code" => "40351",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:04:39",
            "updated_at" => "2018-05-02 14:04:39",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 25,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "James McDaniel",
            "email" => null,
            "phone" => "(765) 337 - 9489",
            "address1" => "5214 Goodard Road",
            "address2" => null,
            "city" => "Wallingford",
            "province_id" => 17,
            "postal_code" => "41093",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:11:28",
            "updated_at" => "2018-05-02 14:11:28",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 26,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Margaret Wright",
            "email" => null,
            "phone" => "(606) 743 - 3007",
            "address1" => "5566 Highway 420 East",
            "address2" => null,
            "city" => "West Liberty",
            "province_id" => 17,
            "postal_code" => "41472",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:13:45",
            "updated_at" => "2018-05-02 14:13:45",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 27,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Robert Wilson",
            "email" => null,
            "phone" => "(859) 248 - 5142",
            "address1" => "1510B Redhouse Rd.",
            "address2" => null,
            "city" => "Richmond",
            "province_id" => 17,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:22:20",
            "updated_at" => "2018-05-02 14:22:20",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 28,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Shawn Thompson",
            "email" => null,
            "phone" => null,
            "address1" => "1588 Highway 60 East",
            "address2" => null,
            "city" => "Owingsville",
            "province_id" => 17,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:36:14",
            "updated_at" => "2018-05-02 14:36:14",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 29,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Jennifer Herron",
            "email" => null,
            "phone" => "(859) 202 - 4502",
            "address1" => "404 West Legen Drive",
            "address2" => null,
            "city" => "Mt. Sterling",
            "province_id" => 17,
            "postal_code" => "40353",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:40:38",
            "updated_at" => "2018-05-02 14:40:38",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 30,
            "creator_id" => 4,
            "owner_id" => 4,
            "name" => "Bobby Cundiff",
            "email" => null,
            "phone" => null,
            "address1" => "520 Highway 599",
            "address2" => null,
            "city" => "Jeffersonville",
            "province_id" => 17,
            "postal_code" => "40353",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-05-02 14:44:31",
            "updated_at" => "2018-05-02 14:44:31",
        ]);
        
        factory(App\Models\Client::class)->create([                        
            "id" => 31,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "James Curtis",
            "email" => null,
            "phone" => null,
            "address1" => null,
            "address2" => null,
            "city" => null,
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-07 17:34:29",
            "updated_at" => "2018-06-07 17:34:29",
        ]);  

        factory(App\Models\Client::class)->create([                        
             "id" => 32,
             "creator_id" => 3,
             "owner_id" => 3,
             "name" => "Ramon Martin",
             "email" => null,
             "phone" => "859-621-1961",
             "address1" => "123 N Sycamore Street",
             "address2" => null,
             "city" => "Mount Sterling",
             "province_id" => 17,
             "postal_code" => "40353",
             "description" => null,
             "deleted_at" => null,
             "created_at" => "2018-06-20 13:41:10",
             "updated_at" => "2018-06-20 13:41:10",
        ]);  

        factory(App\Models\Client::class)->create([                        
            "id" => 33,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Brandon Bowling",
            "email" => null,
            "phone" => null,
            "address1" => null,
            "address2" => null,
            "city" => null,
            "province_id" => null,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-20 14:11:44",
            "updated_at" => "2018-06-20 14:11:44",
        ]);  

        factory(App\Models\Client::class)->create([                        
            "id" => 34,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Robert Sipes",
            "email" => null,
            "phone" => "Not Listed",
            "address1" => "103 Kelsey Drive",
            "address2" => null,
            "city" => "Richmond",
            "province_id" => 17,
            "postal_code" => "40475",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-20 14:19:27",
            "updated_at" => "2018-06-20 14:19:27",
        ]);  

        factory(App\Models\Client::class)->create([                                    
            "id" => 35,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Mary Welch",
            "email" => null,
            "phone" => "859-355-5833",
            "address1" => "16 Fulton Road",
            "address2" => null,
            "city" => "Winchester",
            "province_id" => 17,
            "postal_code" => "40391",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-20 14:31:54",
            "updated_at" => "2018-06-20 14:31:54",
        ]);  

        factory(App\Models\Client::class)->create([                        
            "id" => 36,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Jeramy Wells",
            "email" => null,
            "phone" => "606-782-5718",
            "address1" => "Blount View",
            "address2" => null,
            "city" => "Owingsville",
            "province_id" => 17,
            "postal_code" => "40360",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-20 14:58:51",
            "updated_at" => "2018-06-20 14:58:51",
        ]);  

        factory(App\Models\Client::class)->create([                        
            "id" => 37,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Sarah Jornes",
            "email" => null,
            "phone" => "859-404-8834",
            "address1" => "117 Pulpwood Road",
            "address2" => null,
            "city" => "Olympia",
            "province_id" => 17,
            "postal_code" => "40358",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-20 15:02:39",
            "updated_at" => "2018-06-20 15:02:39",
        ]);  

        factory(App\Models\Client::class)->create([                        
            "id" => 38,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Ellen Machenheimer",
            "email" => null,
            "phone" => "859-653-1849",
            "address1" => null,
            "address2" => null,
            "city" => null,
            "province_id" => 17,
            "postal_code" => null,
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-20 15:20:08",
            "updated_at" => "2018-06-20 15:20:08",
        ]);  

        factory(App\Models\Client::class)->create([                        
            "id" => 39,
            "creator_id" => 3,
            "owner_id" => 3,
            "name" => "Jeramy Wells",
            "email" => null,
            "phone" => "606-782-5718",
            "address1" => "70 Blount View",
            "address2" => null,
            "city" => "Owingsville",
            "province_id" => 17,
            "postal_code" => "40360",
            "description" => null,
            "deleted_at" => null,
            "created_at" => "2018-06-20 15:47:17",
            "updated_at" => "2018-06-20 15:47:17",
        ]);  

    }
}
